# Generated by Django 4.0.4 on 2022-05-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_publish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publish',
            new_name='Reading',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='reading_status',
            new_name='read',
        ),
    ]
